export const COMMENTS_LOAD = 'COMMENTS_LOAD';
export const COMMENTS_CREATE = 'COMMENTS_CREATE';
export const COMMENTS_DELETE = 'COMMENTS_DELETE';
export const COMMENTS_UPDATE = 'COMMENTS_UPDATE';
export const COMMENTS_REPLY = 'COMMENTS_REPLY';
export const COMMENTS_REPLY_DELETE = 'COMMENTS_REPLY_DELETE';
export const COMMENTS_REPLY_UPDATE = 'COMMENTS_REPLY_UPDATE';
